ALTER TABLE trend ALTER COLUMN raw_data TYPE TEXT;
ALTER TABLE pipeline_run ALTER COLUMN stages_json TYPE TEXT;
ALTER TABLE video ALTER COLUMN tags TYPE TEXT;
ALTER TABLE ab_test ALTER COLUMN variants_json TYPE TEXT;
ALTER TABLE ab_test ALTER COLUMN results_json TYPE TEXT;
